### ISSUE TITLE
wdio-selenium-standalone-service requires a peer of selenium-standalone

### ISSUE THREAD

**Issue by f4th4n** [webdriverio-boneyard/wdio-selenium-standalone-service#11]
I tried install on windows, node v6.5

get this error:
`npm WARN wdio-selenium-standalone-service@0.0.6 requires a peer of selenium-standalone@^5.6.0 but none was installed.`

how to fix this?
thankyou

**Comment by klamping** [comment]
Same issue with me. It can be solved by running:
`npm install --save-dev selenium-standalone`

Here's a screenshot of the issue: 
![image](https://cloud.githubusercontent.com/assets/706039/18617612/f9827b46-7d98-11e6-9561-9db1688279e4.png)

This is due to using `peerDependencies` in the package.json listing, which was deprecated in npm v3:
https://github.com/webdriverio/wdio-selenium-standalone-service/blob/master/package.json#L35

Using npm v2, it works just fine.
