### ISSUE TITLE
Selenium Service Does Not Start

### ISSUE THREAD

**Issue by johni1028** [webdriverio-boneyard/wdio-selenium-standalone-service#2]
Environment:
OS X 10.11.4

```
jiracheta$ node_modules/.bin/wdio Mustang/wdio.conf.js 
ERROR: Couldn't connect to selenium server
firefox
    at new RuntimeError (/Users/jiracheta/robo-tester/node_modules/webdriverio/build/lib/utils/ErrorHandler.js:115:12)
    at Request._callback (/Users/jiracheta/robo-tester/node_modules/webdriverio/build/lib/utils/RequestHandler.js:264:37)
    at self.callback (/Users/jiracheta/robo-tester/node_modules/webdriverio/node_modules/request/request.js:373:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:166:7)
    at Request.onRequestError (/Users/jiracheta/robo-tester/node_modules/webdriverio/node_modules/request/request.js:971:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:166:7)
    at Socket.socketErrorListener (_http_client.js:258:9)
    at emitOne (events.js:77:13)
```

```
"dependencies": {
    "webdriverio": "^4.0.5",
    "wdio-mocha-framework": "~0.1",
    "wdio-junit-reporter": "~0.0.1",
    "wdio-allure-reporter": "~0.0.2",
    "appium": "^1.5.1",
    "chai": "^3.5.0"
  },
  "devDependencies": {
    "wdio-selenium-standalone-service": "~0.0.1"
  }
```

```
exports.config = {

    specs: [
        'Mustang/functional/tests/*.js'
    ],

    capabilities: [{
        browserName: 'firefox'
    }],

    logLevel: 'silent',

    coloredLogs: true,

    screenshotPath: 'Mustang/functional/errorShots/',

    baseUrl: 'http://google.com',

    waitforTimeout: 150000,

    connectionRetryTimeout: 90000,

    connectionRetryCount: 3,

    services: ['selenium-standalone'],

    framework: 'mocha',

    reporters: ['dot', 'junit'],
    reporterOptions: {
        outputDir: 'Mustang/functional/reports/'
    },

    mochaOpts: {
        ui: 'bdd'
    },

}
```

**Comment by ondrejsevcik** [comment]
Same problem with windows 8.1

**Comment by lplotni** [comment]
I have the same issue (Mac 10.11.4, Node 5.10.1)

**Comment by hamishtaplin** [comment]
Same problem here (OS X 10.11.3, Node 5.2.0)

**Comment by ondrejsevcik** [comment]
I think it's because the starting point https://github.com/webdriverio/wdio-selenium-standalone-service/blob/master/index.js#L4 exports an empty object.

**Comment by DogPawHat** [comment]
Been having this error on Win 8.1 myself. I forked and cloned the repo myself to download, build and test, and the test failed after running the build, postinstall, and test commands in order.

**Comment by andriilazebnyi** [comment]
The problem is that **./build** folder isn't created during running **npm install wdio-selenium-standalone-service** command.

Package.json contains the following scripts:

```
  "scripts": {
    "postinstall": "selenium-standalone install",
    "build": "grunt build",
    "test": "wdio test/wdio.conf.js"
  }
```

And **launcher.js** contains the following code:

```
var SeleniumLauncher = require('./build/launcher').default
module.exports = new SeleniumLauncher()
```

However, **build** isn't called during install. This happens because **npm build** is an internal npm command and shouldn't be called directly. Also, as it's already exists, it always shadows over scripts's "build".

See those [SO topic](http://stackoverflow.com/questions/29939697/npm-build-doesnt-run-my-build-scripts) and [npm docs](https://docs.npmjs.com/cli/build).

So, I think there are 2 options:
1. build **launcher.js**, put it in **lib** folder and change path to **./lib/launcher**;
2. run **npm run build** in **preinstall** script.

I've created a pull request where **npm run build** is being called in **preinstall** script. However, I'm not sure if that is a proper way to fix this issue.

@christian-bromann please, take a look.

**Comment by christian-bromann** [comment]
Let's move conversation to #3
